[[unzip]]
arch = "aarch64"
git-tree-sha1 = "0c66d68be48bb9f2ccbaf2f3ac0bf38efb3e140a"
os = "macos"

    [[unzip.download]]
    sha256 = "031bd2341105f3260c7c548831dabcc3268e847df5267c551b269c0227afe339"
    url = "https://github.com/JuliaBinaryWrappers/unzip_jll.jl/releases/download/unzip-v6.0.3+0/unzip.v6.0.3.aarch64-apple-darwin.tar.gz"
[[unzip]]
arch = "aarch64"
git-tree-sha1 = "8c9c98d81aa6db40236285c8e7925fe3aeac74d4"
libc = "glibc"
os = "linux"

    [[unzip.download]]
    sha256 = "a65252d0efab25a3d64344c3add93c007df6791c00038f6d17dc23023eb3ee2d"
    url = "https://github.com/JuliaBinaryWrappers/unzip_jll.jl/releases/download/unzip-v6.0.3+0/unzip.v6.0.3.aarch64-linux-gnu.tar.gz"
[[unzip]]
arch = "aarch64"
git-tree-sha1 = "107b08b736a965d9e0fee12e8b34801ace6d2fa9"
libc = "musl"
os = "linux"

    [[unzip.download]]
    sha256 = "506828b4c09ffb2f2bc32093afcbd9188452a4857182f9d75ee539f54034ff69"
    url = "https://github.com/JuliaBinaryWrappers/unzip_jll.jl/releases/download/unzip-v6.0.3+0/unzip.v6.0.3.aarch64-linux-musl.tar.gz"
[[unzip]]
arch = "aarch64"
git-tree-sha1 = "7b6bde79b70d857b909a2f9665b1e5785ab73c8c"
os = "freebsd"

    [[unzip.download]]
    sha256 = "17e6ff5ed63e2160c5d1708f8b874fbbd31579945375902a83f6ce161fe221e7"
    url = "https://github.com/JuliaBinaryWrappers/unzip_jll.jl/releases/download/unzip-v6.0.3+0/unzip.v6.0.3.aarch64-unknown-freebsd.tar.gz"
[[unzip]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "6078bfa4ecfc8f7cb338b862bdd6573e1ac61b59"
libc = "glibc"
os = "linux"

    [[unzip.download]]
    sha256 = "79ee1d952b9ebb16b0829c1ee6270426a2c8e10cae2aa4130ac4bdfac6d1da12"
    url = "https://github.com/JuliaBinaryWrappers/unzip_jll.jl/releases/download/unzip-v6.0.3+0/unzip.v6.0.3.armv6l-linux-gnueabihf.tar.gz"
[[unzip]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "ec8497ba2a41151540ca4ed142d44020d8e1c63e"
libc = "musl"
os = "linux"

    [[unzip.download]]
    sha256 = "983f49dfbd51598a7ce7362009660466b79a548fa9b3056a228e358dd08395b2"
    url = "https://github.com/JuliaBinaryWrappers/unzip_jll.jl/releases/download/unzip-v6.0.3+0/unzip.v6.0.3.armv6l-linux-musleabihf.tar.gz"
[[unzip]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "9e1ea9eb41c0b131baf66f54ae3557fbc57ecd53"
libc = "glibc"
os = "linux"

    [[unzip.download]]
    sha256 = "86d74c855a1fc582c1f130c9795a1a83bdeaff994511ab281ef537485fbf67f5"
    url = "https://github.com/JuliaBinaryWrappers/unzip_jll.jl/releases/download/unzip-v6.0.3+0/unzip.v6.0.3.armv7l-linux-gnueabihf.tar.gz"
[[unzip]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "a7b39adc549dc1959995c6590ddab59ffb720f46"
libc = "musl"
os = "linux"

    [[unzip.download]]
    sha256 = "3d37c16a8a179a2336287e61788f3c217d3f4084f9ce0d19b31470c80599587a"
    url = "https://github.com/JuliaBinaryWrappers/unzip_jll.jl/releases/download/unzip-v6.0.3+0/unzip.v6.0.3.armv7l-linux-musleabihf.tar.gz"
[[unzip]]
arch = "i686"
git-tree-sha1 = "441c868341ca10cdc1a44c97739b188e1fcdc1b5"
libc = "glibc"
os = "linux"

    [[unzip.download]]
    sha256 = "ff75fedd22d09e5a95c14a6b9116f5c32badd04d6b0ae3d2e418f8f4fed0bd56"
    url = "https://github.com/JuliaBinaryWrappers/unzip_jll.jl/releases/download/unzip-v6.0.3+0/unzip.v6.0.3.i686-linux-gnu.tar.gz"
[[unzip]]
arch = "i686"
git-tree-sha1 = "64e9b765b1f33c5e9973ad049ac1b7e6c3d5b1a2"
libc = "musl"
os = "linux"

    [[unzip.download]]
    sha256 = "43f0ec5ff3f2522e80f76c5f9586f604772078bb14e1fdec6de4a15cd05e088b"
    url = "https://github.com/JuliaBinaryWrappers/unzip_jll.jl/releases/download/unzip-v6.0.3+0/unzip.v6.0.3.i686-linux-musl.tar.gz"
[[unzip]]
arch = "i686"
git-tree-sha1 = "05f7784846b8da9131bf6ca7714d44b2d58a1611"
os = "windows"

    [[unzip.download]]
    sha256 = "e39c65bc0972b0d8beafaea610d288e5fae0f1733c94c67b2ee2c9a510790980"
    url = "https://github.com/JuliaBinaryWrappers/unzip_jll.jl/releases/download/unzip-v6.0.3+0/unzip.v6.0.3.i686-w64-mingw32.tar.gz"
[[unzip]]
arch = "powerpc64le"
git-tree-sha1 = "264cc4370258caa6271c270a7126bf502899decd"
libc = "glibc"
os = "linux"

    [[unzip.download]]
    sha256 = "019470289ed3dd14fd3644fe34891566cf98393c5bd440cf4276259cba7207b6"
    url = "https://github.com/JuliaBinaryWrappers/unzip_jll.jl/releases/download/unzip-v6.0.3+0/unzip.v6.0.3.powerpc64le-linux-gnu.tar.gz"
[[unzip]]
arch = "riscv64"
git-tree-sha1 = "fb356a3f47598092d8fa8bf6aa63217128d4cc72"
libc = "glibc"
os = "linux"

    [[unzip.download]]
    sha256 = "8494b69601baca0339ecae3033580103954a95170f04699cf626718f88544c73"
    url = "https://github.com/JuliaBinaryWrappers/unzip_jll.jl/releases/download/unzip-v6.0.3+0/unzip.v6.0.3.riscv64-linux-gnu.tar.gz"
[[unzip]]
arch = "x86_64"
git-tree-sha1 = "a8e21c5d570244f857efffce536892ea784e3705"
os = "macos"

    [[unzip.download]]
    sha256 = "eadd28bbc44e3610e33da7226569b6bdc51d297d70e7a04c76fe5a19f24207bb"
    url = "https://github.com/JuliaBinaryWrappers/unzip_jll.jl/releases/download/unzip-v6.0.3+0/unzip.v6.0.3.x86_64-apple-darwin.tar.gz"
[[unzip]]
arch = "x86_64"
git-tree-sha1 = "d78d7843d41715084457309f21269c3b156939f6"
libc = "glibc"
os = "linux"

    [[unzip.download]]
    sha256 = "3a63b77837c128eeccf657e7545786bd5f241285265f1b450fbddcee2ce08e38"
    url = "https://github.com/JuliaBinaryWrappers/unzip_jll.jl/releases/download/unzip-v6.0.3+0/unzip.v6.0.3.x86_64-linux-gnu.tar.gz"
[[unzip]]
arch = "x86_64"
git-tree-sha1 = "6d574a73306956a04b45d14d8c6893116c1c06f0"
libc = "musl"
os = "linux"

    [[unzip.download]]
    sha256 = "7ca6fcad1a82567db830865d9433449c0586fe7d42ab9e303a0ba770a20a9f33"
    url = "https://github.com/JuliaBinaryWrappers/unzip_jll.jl/releases/download/unzip-v6.0.3+0/unzip.v6.0.3.x86_64-linux-musl.tar.gz"
[[unzip]]
arch = "x86_64"
git-tree-sha1 = "94278d8cd8546072dcc8b3748d37783059e6da7a"
os = "freebsd"

    [[unzip.download]]
    sha256 = "fe72669e129a7a90417f49f0e47ffcad26511b4d2fc452bb2f89728e366e7168"
    url = "https://github.com/JuliaBinaryWrappers/unzip_jll.jl/releases/download/unzip-v6.0.3+0/unzip.v6.0.3.x86_64-unknown-freebsd.tar.gz"
[[unzip]]
arch = "x86_64"
git-tree-sha1 = "10b4ed4f38b954802cc789cebbe797c84bd34fca"
os = "windows"

    [[unzip.download]]
    sha256 = "b59e51f186c522548c46442ec6251fa0e3f137c3dd45cf96c1cd24795d97a163"
    url = "https://github.com/JuliaBinaryWrappers/unzip_jll.jl/releases/download/unzip-v6.0.3+0/unzip.v6.0.3.x86_64-w64-mingw32.tar.gz"
